name: Vyuha
favicon: null
layout_spectrum: 0.29851
typography_spectrum: 0.7829191780183464
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#574e49'
    - '#ffb200'
    - '#817974'
    - '#ab9773'
    - '#ffdd90'
  brandStrength: 0.8125
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
